export const PLATFORM_CHANNELS = {
  IS_DEV: 'PLATFORM_CHANNELS:IS_DEV',
  IS_MAC: 'PLATFORM_CHANNELS:IS_MAC',
  IS_WINDOWS: 'PLATFORM_CHANNELS:IS_WINDOWS',
  IS_LINUX: 'PLATFORM_CHANNELS:IS_LINUX',
} as const;
