export const VERSION_CHANNELS = {
  GET_APP_VERSION: 'VERSION_CHANNELS:GET_APP_VERSION',
  GET_NODE_VERSION: 'VERSION_CHANNELS:GET_NODE_VERSION',
  GET_ELECTRON_VERSION: 'VERSION_CHANNELS:GET_ELECTRON_VERSION',
  GET_CHROME_VERSION: 'VERSION_CHANNELS:GET_CHROME_VERSION',
} as const;
