export const FILE_CHANNELS = {
  CREATE_WORKSPACE: 'FILE_CHANNELS:CREATE_WORKSPACE',
  OPEN_WORKSPACE: 'FILE_CHANNELS:OPEN_WORKSPACE',
  CREATE_FILE: 'FILE_CHANNELS:CREATE_FILE',
  CREATE_FOLDER: 'FILE_CHANNELS:CREATE_FOLDER',
  OPEN_FILE: 'FILE_CHANNELS:OPEN_FILE',
  SAVE_FILE: 'FILE_CHANNELS:SAVE_FILE',
  RENAME_FILE: 'FILE_CHANNELS:RENAME_FILE',
  RENAME_FOLDER: 'FILE_CHANNELS:RENAME_FOLDER',
  DELETE_FILE: 'FILE_CHANNELS:DELETE_FILE',
  DELETE_FOLDER: 'FILE_CHANNELS:DELETE_FOLDER',
} as const;
