export const FILE_CHANNELS = {
  CREATE_WORKSPACE: 'FILE_CHANNELS:CREATE_WORKSPACE',
  OPEN_WORKSPACE: 'FILE_CHANNELS:OPEN_WORKSPACE',
  OPEN_FILE: 'FILE_CHANNELS:OPEN_FILE',
  SAVE_FILE: 'FILE_CHANNELS:SAVE_FILE',
} as const;
