export const LAYOUT_PATHS = {
  NON_WORKSPACE: '/non-workspace',
  WORKSPACE: '/workspace',
};

export const ROUTE_PATHS = {
  WELCOME: '/',
  FOLDER_TREE: '/folder-tree',
  AI_CHAT: '/ai-chat',
  SEARCH: '/search',
  SHARE: '/share',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  HELP: '/help',
};

export const FULL_ROUTE_PATHS = {
  WELCOME: ROUTE_PATHS.WELCOME,
  FOLDER_TREE: `${LAYOUT_PATHS.NON_WORKSPACE}${LAYOUT_PATHS.WORKSPACE}${ROUTE_PATHS.FOLDER_TREE}`,
  AI_CHAT: `${LAYOUT_PATHS.NON_WORKSPACE}${LAYOUT_PATHS.WORKSPACE}${ROUTE_PATHS.AI_CHAT}`,
  SEARCH: `${LAYOUT_PATHS.NON_WORKSPACE}${LAYOUT_PATHS.WORKSPACE}${ROUTE_PATHS.SEARCH}`,
  SHARE: `${LAYOUT_PATHS.NON_WORKSPACE}${ROUTE_PATHS.SHARE}`,
  SETTINGS: `${LAYOUT_PATHS.NON_WORKSPACE}${ROUTE_PATHS.SETTINGS}`,
  PROFILE: `${LAYOUT_PATHS.NON_WORKSPACE}${ROUTE_PATHS.PROFILE}`,
  HELP: `${LAYOUT_PATHS.NON_WORKSPACE}${ROUTE_PATHS.HELP}`,
};
