export const MAIN_TO_RENDERER_EVENTS = {
  CREATE_FOLDER: 'MAIN_TO_RENDERER_EVENTS:CREATE_FOLDER',
  CREATE_FILE: 'MAIN_TO_RENDERER_EVENTS:CREATE_FILE',
  RENAME_FOLDER: 'MAIN_TO_RENDERER_EVENTS:RENAME_FOLDER',
  RENAME_FILE: 'MAIN_TO_RENDERER_EVENTS:RENAME_FILE',
  DELETE_FOLDER: 'MAIN_TO_RENDERER_EVENTS:DELETE_FOLDER',
  DELETE_FILE: 'MAIN_TO_RENDERER_EVENTS:DELETE_FILE',
};
