export const CONTEXT_MENU_CHANNELS = {
  OPEN_FOLDER_TREE_CONTEXT_MENU: 'CONTEXT_MENU_CHANNELS:OPEN_FOLDER_TREE_CONTEXT_MENU',
  OPEN_FOLDER_NODE_CONTEXT_MENU: 'CONTEXT_MENU_CHANNELS:OPEN_FOLDER_NODE_CONTEXT_MENU',
  OPEN_FILE_NODE_CONTEXT_MENU: 'CONTEXT_MENU_CHANNELS:OPEN_FILE_NODE_CONTEXT_MENU',
} as const;
