import { app } from 'electron';
import { Subscriber } from '../app/core/subscriber';
import { AppSubscriber } from '../app/modules/app/app.subscriber';
import { FileSubscriber } from '../app/modules/file/file.subscriber';
import { PlatformSubscriber } from '../app/modules/platform/platform.subscriber';
import { StorageSubscriber } from '../app/modules/storage/storage.subscriber';
import { VersionSubscriber } from '../app/modules/version/version.subscriber';
import { Configs } from './configs';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

class ElectronMainProcess {
  public constructor(
    private readonly appSubscriber: AppSubscriber,
    private readonly subscribers: Subscriber[],
  ) {}

  public start = () => {
    this.checkSquirrelStartup();
    this.appSubscriber.start(MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY, MAIN_WINDOW_WEBPACK_ENTRY);
    this.subscribers.forEach((subscriber) => subscriber.start());
  };

  private checkSquirrelStartup = () => {
    if (Configs.isWindows && require('electron-squirrel-startup')) {
      app.quit();
    }
  };
}

// Init the main process
const electronMainProcess = new ElectronMainProcess(new AppSubscriber(), [
  new VersionSubscriber(),
  new PlatformSubscriber(),
  new FileSubscriber(),
  new StorageSubscriber(),
]);

// Start the main process
electronMainProcess.start();
