import { app } from 'electron';
import { AppSubscriber } from '../app/modules/app';
import { VersionSubscriber } from '../app/modules/version';
import { Configs } from './configs';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

class ElectronMainProcess {
  public constructor(
    private readonly appSubscriber: AppSubscriber,
    private readonly versionSubscriber: VersionSubscriber,
  ) {}

  public start() {
    this.checkSquirrelStartup();
    this.appSubscriber.start(MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY, MAIN_WINDOW_WEBPACK_ENTRY);
    this.versionSubscriber.start();
  }

  private checkSquirrelStartup() {
    if (Configs.isWindows && require('electron-squirrel-startup')) {
      app.quit();
    }
  }
}

// Init listeners
const appSubscriber = new AppSubscriber();
const versionSubscriber = new VersionSubscriber();

// Init the main process
const electronMainProcess = new ElectronMainProcess(appSubscriber, versionSubscriber);
// Start the main process
electronMainProcess.start();
